#pragma once
// Auto-generated by tools/airports_to_header.py — do not edit.
// ICAO airport codes (26439 entries), IATA redirects (7064).
// Source: mwgg/Airports airports.json (city labels + lat/lon centidegrees).

#include <cstddef>
#include <cstdint>

namespace data::airports {

constexpr size_t kCount = 26439;
constexpr size_t kIataCount = 7064;
constexpr size_t kMaxNameLen = 56;

struct Entry {
  char icao[4];
  uint32_t name_offset;
  int16_t lat_centi;
  int16_t lon_centi;
};

struct IataEntry {
  char iata[4];
  char icao[4];
};

extern const char kNames[];
extern const Entry kAirports[kCount];
extern const IataEntry kIataToIcao[kIataCount];

}  // namespace data::airports
