#pragma once
// Auto-generated by tools/icao_types_to_header.py — do not edit.
// ICAO aircraft type designators (1769 entries).
// Source: wiedehopf/tar1090-db aircraft.csv.gz (Mictronics).

#include <cstddef>
#include <cstdint>

namespace data::icao_types {

constexpr size_t kCount = 1769;
constexpr size_t kMaxNameLen = 56;

struct Entry {
  char code[5];
  uint16_t name_offset;
};

extern const char kNames[];
extern const Entry kTypes[kCount];

}  // namespace data::icao_types
