#!/usr/bin/env python3
"""Convert airline logo PNGs to compressed GIF bytes in flash (ICAO lookup).

Adapted from rzeldent/esp32-flightradar24-ttgo images_to_lvgl.py.
Source PNGs: data/airline_logos/airline_logo_{ICAO}.png
"""

from __future__ import annotations

import hashlib
import io
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Pillow required: pip install Pillow")
    sys.exit(1)

MAX_W = 88
MAX_H = 88
DEFAULT_SRC = Path(__file__).resolve().parent.parent / "data" / "airline_logos"
DEFAULT_OUT = (
    Path(__file__).resolve().parent.parent / "include" / "data" / "airline_logos_lookup.h"
)


def parse_icao(png: Path) -> str | None:
    stem = png.stem.upper()
    if stem.startswith("AIRLINE_LOGO_"):
        icao = stem[len("AIRLINE_LOGO_") :]
    else:
        icao = stem
    if len(icao) != 3 or not icao.isalpha():
        return None
    return icao


def resize_preserve_aspect(image: Image.Image, max_w: int, max_h: int) -> Image.Image:
    aspect = image.size[0] / image.size[1]
    if aspect > 1:
        size = (max_w, max(1, int(max_w / aspect)))
    else:
        size = (max(1, int(max_h * aspect)), max_h)
    return image.resize(size, Image.Resampling.LANCZOS)


def emit_u8_array(name: str, data: bytes) -> str:
    lines: list[str] = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        parts = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {parts}")
    body = ",\n".join(lines)
    return f"constexpr uint8_t {name}[] PROGMEM = {{\n{body}\n}};\n"


def main() -> int:
    src_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT

    if not src_dir.is_dir():
        print(f"Skip airline logos: {src_dir} not found")
        return 0

    pngs = sorted(src_dir.glob("*.png"))
    if not pngs:
        print(f"Skip airline logos: no PNGs in {src_dir}")
        return 0

    hashes: dict[str, str] = {}
    duplicates: dict[str, str] = {}
    blob_meta: dict[str, tuple[int, int, int]] = {}
    entries: list[tuple[str, str]] = []
    blob_sources: list[str] = []
    total_bytes = 0

    for png in pngs:
        icao = parse_icao(png)
        if icao is None:
            continue

        image = Image.open(png).convert("RGBA")
        image = resize_preserve_aspect(image, MAX_W, MAX_H)
        digest = hashlib.md5(image.tobytes()).hexdigest()
        sym = f"airline_logo_{icao}"
        w, h = image.size

        if digest not in hashes:
            hashes[digest] = sym
            byte_io = io.BytesIO()
            image.save(byte_io, optimize=True, format="GIF")
            gif = byte_io.getvalue()
            total_bytes += len(gif)
            blob_meta[sym] = (w, h, len(gif))
            blob_sources.append(emit_u8_array(f"{sym}_gif", gif))
            entries.append((icao, sym))
        else:
            canonical = hashes[digest]
            duplicates[sym] = canonical
            entries.append((icao, canonical))

        image.close()

    entries.sort(key=lambda e: e[0])

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as out:
        out.write("// Auto-generated by tools/airline_logos_to_header.py — do not edit.\n")
        out.write("#pragma once\n\n")
        out.write("#include <cstdint>\n\n")
        out.write("namespace data::airline_logos {\n\n")
        out.write(f"constexpr int kMaxLogoW = {MAX_W};\n")
        out.write(f"constexpr int kMaxLogoH = {MAX_H};\n\n")
        out.write("constexpr uint16_t kTransparentRgb565 = 0xF81F;\n\n")

        out.write("struct LogoBlob {\n")
        out.write("  uint16_t w;\n")
        out.write("  uint16_t h;\n")
        out.write("  uint32_t size;\n")
        out.write("  const uint8_t* gif;\n")
        out.write("};\n\n")

        out.write("struct Entry {\n")
        out.write("  char icao[4];\n")
        out.write("  const LogoBlob* logo;\n")
        out.write("};\n\n")

        for src in blob_sources:
            out.write(src)
            out.write("\n")

        for alias, canonical in sorted(duplicates.items()):
            out.write(f"#define {alias}_gif {canonical}_gif\n")
        if duplicates:
            out.write("\n")

        for sym, (w, h, size) in sorted(blob_meta.items()):
            code = sym[len("airline_logo_") :]
            out.write(
                f"constexpr LogoBlob kBlob_{code} = "
                f"{{ {w}, {h}, {size}, {sym}_gif }};\n"
            )
        out.write("\n")

        out.write(f"constexpr size_t kCount = {len(entries)};\n\n")
        out.write("constexpr Entry kEntries[] PROGMEM = {\n")
        for icao, sym in entries:
            code = sym[len("airline_logo_") :]
            out.write(f'  {{"{icao}", &kBlob_{code}}},\n')
        out.write("};\n\n")
        out.write("}  // namespace data::airline_logos\n")

    print(
        f"Wrote {out_path}: {len(entries)} logos, "
        f"{len(blob_meta)} unique GIFs ({total_bytes / 1024:.0f} KiB), "
        f"{len(duplicates)} aliases"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
