#!/usr/bin/env python3
"""Build ICAO -> city and IATA -> ICAO tables for PROGMEM lookup.

Default source: mwgg/Airports airports.json (ICAO-keyed, uses city field).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

MWGG_AIRPORTS_URL = (
    "https://raw.githubusercontent.com/mwgg/Airports/master/airports.json"
)

ICAO = re.compile(r"^[A-Z0-9]{4}$")
IATA = re.compile(r"^[A-Z]{3}$")
MAX_NAME_LEN = 56


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def cache_path() -> Path:
    return Path(__file__).resolve().parent / ".cache" / "airports.json"


def default_header_path() -> Path:
    return repo_root() / "include" / "data" / "airports_lookup.h"


def default_cpp_path() -> Path:
    return repo_root() / "src" / "data" / "airports_lookup.cpp"


def download_json(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(url, timeout=120) as resp:
        data = resp.read()
    dest.write_bytes(data)


def airport_city(entry: dict) -> str:
    city = " ".join((entry.get("city") or "").split())
    return city[:MAX_NAME_LEN]


def lat_lon_centi(entry: dict) -> tuple[int, int]:
    try:
        lat = int(round(float(entry.get("lat", 0.0)) * 100.0))
        lon = int(round(float(entry.get("lon", 0.0)) * 100.0))
    except (TypeError, ValueError):
        return 0, 0
    lat = max(-9000, min(9000, lat))
    lon = max(-18000, min(18000, lon))
    return lat, lon


def build_maps(data: dict) -> tuple[dict[str, tuple[str, int, int]], dict[str, str]]:
    icao_names: dict[str, tuple[str, int, int]] = {}
    iata_to_icao: dict[str, str] = {}

    for icao_key, entry in data.items():
        if not isinstance(entry, dict):
            continue

        icao = (entry.get("icao") or icao_key or "").strip().upper()
        if not ICAO.match(icao):
            continue

        city = airport_city(entry)
        if not city:
            continue

        lat_c, lon_c = lat_lon_centi(entry)
        icao_names[icao] = (city, lat_c, lon_c)

        iata = (entry.get("iata") or "").strip().upper()
        if IATA.match(iata) and iata not in iata_to_icao:
            iata_to_icao[iata] = icao

    return dict(sorted(icao_names.items())), dict(sorted(iata_to_icao.items()))


def c_pool_bytes(names: list[str]) -> str:
    """Emit kNames as a hex byte initializer — avoids C string-literal escape traps."""
    tokens: list[str] = []
    for name in names:
        for byte in name.encode("utf-8"):
            tokens.append(f"0x{byte:02x}")
        tokens.append("0x00")
    lines: list[str] = []
    for i in range(0, len(tokens), 16):
        lines.append("  " + ", ".join(tokens[i : i + 16]) + ",")
    return "\n".join(lines)


def c_chars4(code: str) -> str:
    return ", ".join(f"'{c}'" for c in code[:4])


def c_iata4(iata: str) -> str:
    return ", ".join(f"'{c}'" for c in iata[:3]) + ", '\\0'"


def write_outputs(
    icao_names: dict[str, tuple[str, int, int]],
    iata_to_icao: dict[str, str],
    header_path: Path,
    cpp_path: Path,
) -> None:
    icao_entries = sorted(icao_names.items())
    iata_entries = sorted(iata_to_icao.items())

    names: list[str] = []
    name_index: dict[str, int] = {}

    def pool_offset(name: str) -> int:
        clipped = name[:MAX_NAME_LEN]
        if clipped not in name_index:
            name_index[clipped] = sum(len(n.encode("utf-8")) + 1 for n in names)
            names.append(clipped)
        return name_index[clipped]

    icao_rows = [
        f"  {{ {{ {c_chars4(code)} }}, {pool_offset(name)}, {lat_c}, {lon_c} }},"
        for code, (name, lat_c, lon_c) in icao_entries
    ]
    iata_rows = [
        f"  {{ {{ {c_iata4(iata)} }}, {{ {c_chars4(icao)} }} }},"
        for iata, icao in iata_entries
    ]
    names_blob = c_pool_bytes(names)

    header = f"""#pragma once
// Auto-generated by tools/airports_to_header.py — do not edit.
// ICAO airport codes ({len(icao_entries)} entries), IATA redirects ({len(iata_entries)}).
// Source: mwgg/Airports airports.json (city labels + lat/lon centidegrees).

#include <cstddef>
#include <cstdint>

namespace data::airports {{

constexpr size_t kCount = {len(icao_entries)};
constexpr size_t kIataCount = {len(iata_entries)};
constexpr size_t kMaxNameLen = {MAX_NAME_LEN};

struct Entry {{
  char icao[4];
  uint32_t name_offset;
  int16_t lat_centi;
  int16_t lon_centi;
}};

struct IataEntry {{
  char iata[4];
  char icao[4];
}};

extern const char kNames[];
extern const Entry kAirports[kCount];
extern const IataEntry kIataToIcao[kIataCount];

}}  // namespace data::airports
"""

    cpp = f"""// Auto-generated by tools/airports_to_header.py — do not edit.
#include "data/airports_lookup.h"

#include <pgmspace.h>

namespace data::airports {{

const char kNames[] PROGMEM = {{
{names_blob}
}};

const Entry kAirports[kCount] PROGMEM = {{
{chr(10).join(icao_rows)}
}};

const IataEntry kIataToIcao[kIataCount] PROGMEM = {{
{chr(10).join(iata_rows)}
}};

}}  // namespace data::airports
"""

    header_path.parent.mkdir(parents=True, exist_ok=True)
    cpp_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text(header, encoding="utf-8")
    cpp_path.write_text(cpp, encoding="utf-8")


def outputs_exist(header_path: Path, cpp_path: Path) -> bool:
    return header_path.is_file() and cpp_path.is_file()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--input", type=Path, default=None)
    parser.add_argument("-o", "--output", type=Path, default=default_header_path())
    parser.add_argument("--offline", action="store_true")
    args = parser.parse_args()

    header_path = args.output
    cpp_path = default_cpp_path()
    cached = cache_path()

    json_path: Path | None = args.input
    if json_path is None and not args.offline:
        try:
            print(f"airports: downloading {MWGG_AIRPORTS_URL}")
            download_json(MWGG_AIRPORTS_URL, cached)
            json_path = cached
        except (OSError, urllib.error.URLError) as exc:
            print(f"airports: download failed ({exc})")
            if cached.is_file():
                print(f"airports: using cached {cached}")
                json_path = cached
    elif json_path is None and cached.is_file():
        json_path = cached

    if json_path is None or not json_path.is_file():
        if outputs_exist(header_path, cpp_path):
            print("airports: keeping existing generated lookup files")
            return 0
        print("airports: no input and no existing generated files", file=sys.stderr)
        return 1

    data = json.loads(json_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        print("airports: expected JSON object at root", file=sys.stderr)
        return 1

    icao_names, iata_to_icao = build_maps(data)
    if not icao_names:
        print("airports: no airport entries parsed", file=sys.stderr)
        return 1

    write_outputs(icao_names, iata_to_icao, header_path, cpp_path)
    print(f"Wrote {header_path} and {cpp_path}")
    print(f"  ICAO {len(icao_names)}  IATA {len(iata_to_icao)}")
    print(
        "  Sample: "
        f"SFO->{icao_names.get(iata_to_icao.get('SFO', ''), ('?', 0, 0))[0]} "
        f"PVG->{icao_names.get(iata_to_icao.get('PVG', ''), ('?', 0, 0))[0]} "
        f"KSFO={icao_names.get('KSFO', ('?', 0, 0))[0]}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
